#!/bin/bash
go_client=/home/marlon/Src/katran/katran_goclient
katran_server_grpc_exe=/home/marlon/Src/katran/_build/build/example_grpc/katran_server_grpc 
#ebpf_prog=/home/marlon/Src/katran/_build/deps/bpfprog/bpf/balancer_kern.o
ebpf_prog=/home/marlon/Src/katran/_build/deps/bpfprog/bpf/balancer_kern_minimal.o
real_servers_prefix="192.168.17"
host_sequence=$(seq 180 180)
vip=10.255.255.254:9998
source_ports="44436" 
source_address="192.168.122.1"
